agent_name: autonomous_hegician
author: 8baller
version: 0.1.0
description: An AEA to deploy and interact with an ERC1155
license: Apache-2.0
aea_version: '>=0.5.0, <0.6.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.3.0
- fetchai/stub:0.8.0
contracts:
- fetchai/erc1155:0.8.0
- tomrae/calloptions:0.1.0
- tomrae/ercpool:0.1.0
- tomrae/ethpool:0.1.0
- tomrae/exchange:0.1.0
- tomrae/pricefeed:0.1.0
- tomrae/putoptions:0.1.0
- tomrae/stablecoin:0.1.0
protocols:
- fetchai/contract_api:0.2.0
- fetchai/default:0.4.0
- fetchai/fipa:0.5.0
- fetchai/ledger_api:0.2.0
- fetchai/signing:0.2.0
skills:
- fetchai/error:0.4.0
- tomrae/option_monitoring:0.1.0
default_connection: fetchai/ledger:0.3.0
default_ledger: ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  ethereum: eth_private_key.txt
registry_path: ../packages
default_routing:
  fetchai/contract_api:0.2.0: fetchai/ledger:0.3.0
  fetchai/ledger_api:0.2.0: fetchai/ledger:0.3.0
