version: "3.0"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - './frontend/node_modules:/app/node_modules'
    ports:
        - '3001:3000'
    environment:
      - NODE_ENV=development
  postgresdb:
    ports:
      - "5432:5432"
    image: postgres:latest
    volumes:
        - ./persistant_data/postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: cortex
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: WKLpwoDJd03DJ423DJwlDJlaDJsdDJsdDJlDJsa
  ganachecli:
    build: 
      context: ./ganachecli/
      dockerfile: Dockerfile
    ports:
      - "7545:7545"
    volumes:
      - ./persistant_data/ganache_data:/ganache_data
  api:
    environment:
      TESTS: "False"
      DEBUG: "False"
      RUN_CMD: "pipenv run start_api" 
    build:
      context: ./agents
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    ports:
      - '8080:8080'
    restart: always

  agents:
    environment:
      TESTS: "False"
      DEBUG: "True"
      RUN_CMD: "pipenv run start_agent"
    build:
      context: ./agents
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
      - ganachecli
    volumes:
      - './agents:/app'
    restart: always
