version: "3.0"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
        - '3001:3000'
    environment:
      - NODE_ENV=development
  postgresdb:
    ports:
      - "5432:5432"
    image: postgres:latest
    volumes:
        - ./persistant_data/postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: hippocampus
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: WKLpwoDJd03DJ423DJwlDJlaDJsdDJsdDJlDJsa
  ganachecli:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "7545:7545"
    volumes:
      - ./persistant_data/ganache_data:/ganache_data
    entrypoint:
      - node
      - "/app/ganache-core.docker.cli.js"
      - -s
      - "0"
      - -p
      - "7545"
  agents:
    environment:
      TESTS: "False"
      DEBUG: "False"
      RUN_CMD: "pipenv run launch"
    build:
      context: ./fetch
      dockerfile: Dockerfile
    ports:
        - '8080:8080'
    volumes:
      - './fetch:/app'
    restart: always
