agent_name: autonomous_hegician
author: eightballer
version: 0.1.0
description: An AEA to manage hegic options autonomously
license: Apache-2.0
aea_version: '>=0.7.0, <0.8.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.9.0
- fetchai/p2p_libp2p:0.12.0
contracts:
- eightballer/btcoptions:0.1.0
- eightballer/btcpool:0.1.0
- eightballer/btcpriceprovider:0.1.0
- eightballer/ethoptions:0.1.0
- eightballer/ethpool:0.1.0
- eightballer/exchange:0.1.0
- eightballer/hegic:0.1.0
- eightballer/priceprovider:0.1.0
- eightballer/stakingeth:0.1.0
- eightballer/stakingwbtc:0.1.0
- eightballer/wbtc:0.1.0
protocols:
- fetchai/contract_api:0.8.0
- fetchai/default:0.9.0
- fetchai/ledger_api:0.7.0
- fetchai/signing:0.7.0
- fetchai/state_update:0.7.0
skills:
- eightballer/option_management:0.1.0
- fetchai/error:0.9.0
default_connection: fetchai/p2p_libp2p:0.12.0
default_ledger: ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  ethereum: ethereum_private_key.txt
registry_path: ../packages
default_routing:
  fetchai/contract_api:0.8.0: fetchai/ledger:0.9.0
  fetchai/ledger_api:0.7.0: fetchai/ledger:0.9.0
connection_private_key_paths: {}
---
public_id: eightballer/option_management:0.1.0
type: skill
models:
  strategy:
    args:
      btcoptions: '0xf5A7BBB74dBd1FB6A23eb26a8ADc0D36FE539284'
      btcpool: '0xd9c2EDC1b22481c4Dfe821280f7279AcC094172F'
      btcpriceprovider: '0xd289531C3a34cE4dAB914D1606bBc48080a166F4'
      ethoptions: '0x32D2c3d0332bA1F07BA9EDeafCc288F37072ce6D'
      ethpool: '0xbCc94A15677C700f997c5956071B83C58E401bb9'
      exchange: '0x17c81cA853B2Cb808AFD21f4E54ac233876B673F'
      hegic: '0x952138eABf80658B25Def95cb5e93A7d1EE22922'
      priceprovider: '0x83A0963C0450Cd3E15F61Bbc7586a6bbe6f3Ab2c'
      stakingeth: '0x54a600f55d933f633CeB6B755CD3177eF66e2149'
      stakingwbtc: '0x187284aF7aD0f74169828778410D3Df3B7938cE7'
      wbtc: '0xF9dDAe6AD22737a73533DAA9B7709f68601B3a5f'
