aea_version: '>=0.7.0, <0.8.0'
author: eightballer
behaviours:
  service_registration:
    args:
      services_interval: 0.0001
    class_name: ServiceRegistrationBehaviour
connections:
- fetchai/ledger:0.9.0
contracts:
- eightballer/btcoptions:0.1.0
- eightballer/btcpool:0.1.0
- eightballer/btcpriceprovider:0.1.0
- eightballer/ethoptions:0.1.0
- eightballer/ethpool:0.1.0
- eightballer/exchange:0.1.0
- eightballer/hegic:0.1.0
- eightballer/priceprovider:0.1.0
- eightballer/stakingeth:0.1.0
- eightballer/stakingwbtc:0.1.0
- eightballer/wbtc:0.1.0
dependencies: {}
description: The hegic deploy skill has the ability to deploy and interact with the
  smart contracts.
fingerprint:
  README.md: QmZ7swVkRpmJbJZ2NoLb9CWwH8p3QjnjRJg71UbAXdrKyx
  __init__.py: QmanmQfdWSEPtEKJCt6sz6S13ju3o7D7oSzriBkVABAARj
  behaviours.py: QmZhgmKbBQkM5jvLfuf4JH5CSq21661xyccvZSiYQQsx7H
  dialogues.py: QmTYVyD9o8qNFwiKQGHxGjmXTzeSVShdXNq4pXpVxvdjoo
  handlers.py: QmRre8azW3ZM9zKYpWgwPEJMujtmfNzAEAzK8wkN94hPNS
  strategy.py: QmRnwSbH6bb62NWPKi4HhR1dg9sUh8dLfkXkWSGibjipY3
fingerprint_ignore_patterns: []
handlers:
  contract_api:
    args: {}
    class_name: ContractApiHandler
  ledger_api:
    args: {}
    class_name: LedgerApiHandler
  signing:
    args: {}
    class_name: SigningHandler
is_abstract: false
license: Apache-2.0
models:
  contract_api_dialogues:
    args: {}
    class_name: ContractApiDialogues
  ledger_api_dialogues:
    args: {}
    class_name: LedgerApiDialogues
  signing_dialogues:
    args: {}
    class_name: SigningDialogues
  strategy:
    args:
      btcoptions: ''
      btcpool: ''
      btcpriceprovider: ''
      ethoptions: ''
      ethpool: ''
      exchange: ''
      hegic: ''
      ledger_id: ethereum
      priceprovider: ''
      stakingeth: ''
      stakingwbtc: ''
      wbtc: ''
    class_name: Strategy
name: hegic_deployer
protocols:
- fetchai/contract_api:0.8.0
- fetchai/ledger_api:0.7.0
- fetchai/signing:0.7.0
skills: []
type: skill
version: 0.1.0
