agent_name: tac_controller_contract
author: fetchai
version: 0.9.0
description: An AEA to manage an instance of the TAC (trading agent competition) using
  an ERC1155 smart contract.
license: Apache-2.0
aea_version: '>=0.6.0, <0.7.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/oef:0.8.0
- fetchai/stub:0.9.0
contracts:
- fetchai/erc1155:0.9.0
protocols:
- fetchai/default:0.5.0
- fetchai/fipa:0.6.0
- fetchai/oef_search:0.5.0
- fetchai/tac:0.6.0
skills:
- fetchai/error:0.5.0
- fetchai/tac_control_contract:0.7.0
default_connection: fetchai/oef:0.8.0
default_ledger: ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
