agent_name: erc1155_deployer
author: fetchai
version: 0.16.0
description: An AEA to deploy and interact with an ERC1155
license: Apache-2.0
aea_version: '>=0.7.0, <0.8.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.8.0
- fetchai/p2p_libp2p:0.12.0
- fetchai/soef:0.11.0
contracts:
- fetchai/erc1155:0.12.0
protocols:
- fetchai/contract_api:0.7.0
- fetchai/default:0.8.0
- fetchai/fipa:0.9.0
- fetchai/ledger_api:0.6.0
- fetchai/oef_search:0.9.0
- fetchai/signing:0.6.0
- fetchai/state_update:0.6.0
skills:
- fetchai/erc1155_deploy:0.16.0
- fetchai/error:0.8.0
default_connection: fetchai/p2p_libp2p:0.12.0
default_ledger: ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  ethereum: ethereum_private_key.txt
registry_path: ../packages
default_routing:
  fetchai/contract_api:0.7.0: fetchai/ledger:0.8.0
  fetchai/ledger_api:0.6.0: fetchai/ledger:0.8.0
  fetchai/oef_search:0.9.0: fetchai/soef:0.11.0
connection_private_key_paths: {}
