agent_name: tac_participant
author: fetchai
version: 0.9.0
description: An AEA to participate in the TAC (trading agent competition)
license: Apache-2.0
aea_version: '>=0.6.0, <0.7.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.4.0
- fetchai/p2p_libp2p:0.8.0
- fetchai/soef:0.7.0
- fetchai/stub:0.9.0
contracts:
- fetchai/erc1155:0.9.0
protocols:
- fetchai/default:0.5.0
- fetchai/fipa:0.6.0
- fetchai/oef_search:0.5.0
- fetchai/tac:0.6.0
skills:
- fetchai/error:0.5.0
- fetchai/tac_negotiation:0.8.0
- fetchai/tac_participation:0.7.0
default_connection: fetchai/p2p_libp2p:0.8.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
default_routing:
  fetchai/ledger_api:0.3.0: fetchai/ledger:0.4.0
  fetchai/oef_search:0.5.0: fetchai/soef:0.7.0
