agent_name: hegic_deployer
author: eightballer
version: 0.1.0
description: An AEA to deploy hegic smart contracts
license: Apache-2.0
aea_version: '>=0.7.0, <0.8.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.9.0
- fetchai/p2p_libp2p:0.12.0
contracts:
- eightballer/btcoptions:0.1.0
- eightballer/btcpool:0.1.0
- eightballer/btcpriceprovider:0.1.0
- eightballer/ethoptions:0.1.0
- eightballer/ethpool:0.1.0
- eightballer/exchange:0.1.0
- eightballer/hegic:0.1.0
- eightballer/priceprovider:0.1.0
- eightballer/stakingeth:0.1.0
- eightballer/stakingwbtc:0.1.0
- eightballer/wbtc:0.1.0
protocols:
- fetchai/contract_api:0.8.0
- fetchai/default:0.9.0
- fetchai/ledger_api:0.7.0
- fetchai/signing:0.7.0
- fetchai/state_update:0.7.0
skills:
- eightballer/hegic_deployer:0.1.0
- fetchai/error:0.9.0
default_connection: fetchai/p2p_libp2p:0.12.0
default_ledger: ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  ethereum: ethereum_private_key.txt
registry_path: ../packages
default_routing:
  fetchai/contract_api:0.8.0: fetchai/ledger:0.9.0
  fetchai/ledger_api:0.7.0: fetchai/ledger:0.9.0
connection_private_key_paths: {}
---
public_id: eightballer/hegic_deployer:0.1.0
type: skill
models:
  strategy:
    args:
      btcoptions: ''
      btcpool: ''
      btcpriceprovider: ''
      ethoptions: ''
      ethpool: ''
      exchange: ''
      hegic: ''
      priceprovider: ''
      stakingeth: ''
      stakingwbtc: ''
      wbtc: ''
