agent_name: aries_alice
author: fetchai
version: 0.9.0
description: An AEA representing Alice in the Aries demo.
license: Apache-2.0
aea_version: '>=0.6.0, <0.7.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/http_client:0.8.0
- fetchai/p2p_libp2p:0.8.0
- fetchai/soef:0.7.0
- fetchai/stub:0.9.0
- fetchai/webhook:0.6.0
contracts: []
protocols:
- fetchai/default:0.5.0
- fetchai/http:0.5.0
- fetchai/oef_search:0.5.0
skills:
- fetchai/aries_alice:0.6.0
- fetchai/error:0.5.0
default_connection: fetchai/p2p_libp2p:0.8.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
default_routing:
  fetchai/http:0.5.0: fetchai/http_client:0.8.0
  fetchai/oef_search:0.5.0: fetchai/soef:0.7.0
